#!/usr/bin/env bash
#
# tests/prepend_context.sh - test helpers can source this to standardize generated test fixtures
set -euo pipefail

prepend_header() {
  cat <<'HEADER'
# Test fixture header (R_U_UNI)
# Helps identify autogenerated test data.
HEADER
}

export -f prepend_header
