# Run GS harness on pull requests and upload artifacts
name: GS Check
on:
  pull_request:
    branches: [ main ]
jobs:
  gs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install deps
      run: |
        python -m venv .venv
        . .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run GS harness
      run: |
        . .venv/bin/activate
        ./scripts/run_gs_battery.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: gs-artifacts
        path: |
          /home/runner/UNIBOT_reports/**
