name: Live Rebuild PR Checks

on:
  pull_request:
    branches:
      - 'rebuild/*'

jobs:
  seed-scan-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run deterministic seed scan (dry-run)
        run: |
          python tools/purge_deterministic.py --root . --out .state/deterministic_findings.json
          cat .state/deterministic_findings.json

      - name: Run tests
        run: |
          pytest -q
